ERROR:root:Exception in threaded run()!
Traceback (most recent call last):
  File "pyoscope.py", line 567, in run
    self._update()
  File "pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "pyoscope.py", line 579, in _update
    self._update_dict[self.mode]()
  File "pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "pyoscope.py", line 602, in _update_plot
    update_backend[self._backend]()
  File "pyoscope.py", line 631, in _update_plot_slow
    line = self.lines[i, j]
IndexError: index 1 is out of bounds for axis 1 with size 1
ERROR:root:Exception in threaded run()!
Traceback (most recent call last):
  File "pyoscope.py", line 567, in run
    def run(self):
  File "pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "pyoscope.py", line 579, in _update
    def _update(self):
  File "pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "pyoscope.py", line 602, in _update_plot
    update_backend = {'macosx': self._update_plot_slow,
  File "pyoscope.py", line 631, in _update_plot_slow
    for j, y in enumerate(ys):
IndexError: index 1 is out of bounds for axis 1 with size 1
ERROR:root:Exception in threaded run()!
Traceback (most recent call last):
  File "pyoscope.py", line 567, in run
    def run(self):
  File "pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "pyoscope.py", line 579, in _update
    def _update(self):
  File "pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "pyoscope.py", line 602, in _update_plot
    update_backend = {'macosx': self._update_plot_slow,
  File "pyoscope.py", line 631, in _update_plot_slow
    for j, y in enumerate(ys):
IndexError: index 1 is out of bounds for axis 1 with size 1
ERROR:root:Exception in threaded run()!
Traceback (most recent call last):
  File "/Users/jlazear/github/pyoscope/pyoscope.py", line 571, in run
    self._update()
  File "/Users/jlazear/github/pyoscope/pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "/Users/jlazear/github/pyoscope/pyoscope.py", line 583, in _update
    self.flush()
  File "/Users/jlazear/github/pyoscope/pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "/Users/jlazear/github/pyoscope/pyoscope.py", line 591, in flush
    self.canvas.flush()
AttributeError: 'FigureCanvasMac' object has no attribute 'flush'
ERROR:root:Exception in threaded run()!
Traceback (most recent call last):
  File "pyoscope.py", line 575, in run
    self._update()
  File "pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "pyoscope.py", line 587, in _update
    self.flush()  #DELME?
  File "pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "pyoscope.py", line 596, in flush
    self.canvas.flush_events()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2230, in flush_events
    raise NotImplementedError
NotImplementedError
ERROR:root:Exception in threaded run()!
Traceback (most recent call last):
  File "pyoscope.py", line 576, in run
    self._update()
  File "pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "pyoscope.py", line 587, in _update
    self.canvas.stop_
AttributeError: 'FigureCanvasMac' object has no attribute 'stop_'
ERROR:root:Exception in threaded run()!
Traceback (most recent call last):
  File "pyoscope.py", line 575, in run
    self._update()
  File "pyoscope.py", line 61, in _synchronizer
    return func(self, *args, **kwargs)
  File "pyoscope.py", line 589, in _update
    self.canvas.start_event_loop()
TypeError: Required argument 'timeout' (pos 1) not found
